// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package financiamento

import (
	fmt "fmt"
	io "io"
	reflect "reflect"
	sync "sync"

	runtime "github.com/cosmos/cosmos-proto/runtime"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

var (
	md_Emprestimo         protoreflect.MessageDescriptor
	fd_Emprestimo_id      protoreflect.FieldDescriptor
	fd_Emprestimo_valor   protoreflect.FieldDescriptor
	fd_Emprestimo_prazo   protoreflect.FieldDescriptor
	fd_Emprestimo_taxa    protoreflect.FieldDescriptor
	fd_Emprestimo_devedor protoreflect.FieldDescriptor
	fd_Emprestimo_credor  protoreflect.FieldDescriptor
)

func init() {
	file_defihub_financiamento_emprestimo_proto_init()
	md_Emprestimo = File_defihub_financiamento_emprestimo_proto.Messages().ByName("Emprestimo")
	fd_Emprestimo_id = md_Emprestimo.Fields().ByName("id")
	fd_Emprestimo_valor = md_Emprestimo.Fields().ByName("valor")
	fd_Emprestimo_prazo = md_Emprestimo.Fields().ByName("prazo")
	fd_Emprestimo_taxa = md_Emprestimo.Fields().ByName("taxa")
	fd_Emprestimo_devedor = md_Emprestimo.Fields().ByName("devedor")
	fd_Emprestimo_credor = md_Emprestimo.Fields().ByName("credor")
}

var _ protoreflect.Message = (*fastReflection_Emprestimo)(nil)

type fastReflection_Emprestimo Emprestimo

func (x *Emprestimo) ProtoReflect() protoreflect.Message {
	return (*fastReflection_Emprestimo)(x)
}

func (x *Emprestimo) slowProtoReflect() protoreflect.Message {
	mi := &file_defihub_financiamento_emprestimo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_Emprestimo_messageType fastReflection_Emprestimo_messageType
var _ protoreflect.MessageType = fastReflection_Emprestimo_messageType{}

type fastReflection_Emprestimo_messageType struct{}

func (x fastReflection_Emprestimo_messageType) Zero() protoreflect.Message {
	return (*fastReflection_Emprestimo)(nil)
}
func (x fastReflection_Emprestimo_messageType) New() protoreflect.Message {
	return new(fastReflection_Emprestimo)
}
func (x fastReflection_Emprestimo_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_Emprestimo
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_Emprestimo) Descriptor() protoreflect.MessageDescriptor {
	return md_Emprestimo
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_Emprestimo) Type() protoreflect.MessageType {
	return _fastReflection_Emprestimo_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_Emprestimo) New() protoreflect.Message {
	return new(fastReflection_Emprestimo)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_Emprestimo) Interface() protoreflect.ProtoMessage {
	return (*Emprestimo)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_Emprestimo) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Id != uint64(0) {
		value := protoreflect.ValueOfUint64(x.Id)
		if !f(fd_Emprestimo_id, value) {
			return
		}
	}
	if x.Valor != uint64(0) {
		value := protoreflect.ValueOfUint64(x.Valor)
		if !f(fd_Emprestimo_valor, value) {
			return
		}
	}
	if x.Prazo != uint64(0) {
		value := protoreflect.ValueOfUint64(x.Prazo)
		if !f(fd_Emprestimo_prazo, value) {
			return
		}
	}
	if x.Taxa != "" {
		value := protoreflect.ValueOfString(x.Taxa)
		if !f(fd_Emprestimo_taxa, value) {
			return
		}
	}
	if x.Devedor != "" {
		value := protoreflect.ValueOfString(x.Devedor)
		if !f(fd_Emprestimo_devedor, value) {
			return
		}
	}
	if x.Credor != "" {
		value := protoreflect.ValueOfString(x.Credor)
		if !f(fd_Emprestimo_credor, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_Emprestimo) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "defihub.financiamento.Emprestimo.id":
		return x.Id != uint64(0)
	case "defihub.financiamento.Emprestimo.valor":
		return x.Valor != uint64(0)
	case "defihub.financiamento.Emprestimo.prazo":
		return x.Prazo != uint64(0)
	case "defihub.financiamento.Emprestimo.taxa":
		return x.Taxa != ""
	case "defihub.financiamento.Emprestimo.devedor":
		return x.Devedor != ""
	case "defihub.financiamento.Emprestimo.credor":
		return x.Credor != ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: defihub.financiamento.Emprestimo"))
		}
		panic(fmt.Errorf("message defihub.financiamento.Emprestimo does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Emprestimo) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "defihub.financiamento.Emprestimo.id":
		x.Id = uint64(0)
	case "defihub.financiamento.Emprestimo.valor":
		x.Valor = uint64(0)
	case "defihub.financiamento.Emprestimo.prazo":
		x.Prazo = uint64(0)
	case "defihub.financiamento.Emprestimo.taxa":
		x.Taxa = ""
	case "defihub.financiamento.Emprestimo.devedor":
		x.Devedor = ""
	case "defihub.financiamento.Emprestimo.credor":
		x.Credor = ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: defihub.financiamento.Emprestimo"))
		}
		panic(fmt.Errorf("message defihub.financiamento.Emprestimo does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_Emprestimo) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "defihub.financiamento.Emprestimo.id":
		value := x.Id
		return protoreflect.ValueOfUint64(value)
	case "defihub.financiamento.Emprestimo.valor":
		value := x.Valor
		return protoreflect.ValueOfUint64(value)
	case "defihub.financiamento.Emprestimo.prazo":
		value := x.Prazo
		return protoreflect.ValueOfUint64(value)
	case "defihub.financiamento.Emprestimo.taxa":
		value := x.Taxa
		return protoreflect.ValueOfString(value)
	case "defihub.financiamento.Emprestimo.devedor":
		value := x.Devedor
		return protoreflect.ValueOfString(value)
	case "defihub.financiamento.Emprestimo.credor":
		value := x.Credor
		return protoreflect.ValueOfString(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: defihub.financiamento.Emprestimo"))
		}
		panic(fmt.Errorf("message defihub.financiamento.Emprestimo does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Emprestimo) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "defihub.financiamento.Emprestimo.id":
		x.Id = value.Uint()
	case "defihub.financiamento.Emprestimo.valor":
		x.Valor = value.Uint()
	case "defihub.financiamento.Emprestimo.prazo":
		x.Prazo = value.Uint()
	case "defihub.financiamento.Emprestimo.taxa":
		x.Taxa = value.Interface().(string)
	case "defihub.financiamento.Emprestimo.devedor":
		x.Devedor = value.Interface().(string)
	case "defihub.financiamento.Emprestimo.credor":
		x.Credor = value.Interface().(string)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: defihub.financiamento.Emprestimo"))
		}
		panic(fmt.Errorf("message defihub.financiamento.Emprestimo does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Emprestimo) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "defihub.financiamento.Emprestimo.id":
		panic(fmt.Errorf("field id of message defihub.financiamento.Emprestimo is not mutable"))
	case "defihub.financiamento.Emprestimo.valor":
		panic(fmt.Errorf("field valor of message defihub.financiamento.Emprestimo is not mutable"))
	case "defihub.financiamento.Emprestimo.prazo":
		panic(fmt.Errorf("field prazo of message defihub.financiamento.Emprestimo is not mutable"))
	case "defihub.financiamento.Emprestimo.taxa":
		panic(fmt.Errorf("field taxa of message defihub.financiamento.Emprestimo is not mutable"))
	case "defihub.financiamento.Emprestimo.devedor":
		panic(fmt.Errorf("field devedor of message defihub.financiamento.Emprestimo is not mutable"))
	case "defihub.financiamento.Emprestimo.credor":
		panic(fmt.Errorf("field credor of message defihub.financiamento.Emprestimo is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: defihub.financiamento.Emprestimo"))
		}
		panic(fmt.Errorf("message defihub.financiamento.Emprestimo does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_Emprestimo) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "defihub.financiamento.Emprestimo.id":
		return protoreflect.ValueOfUint64(uint64(0))
	case "defihub.financiamento.Emprestimo.valor":
		return protoreflect.ValueOfUint64(uint64(0))
	case "defihub.financiamento.Emprestimo.prazo":
		return protoreflect.ValueOfUint64(uint64(0))
	case "defihub.financiamento.Emprestimo.taxa":
		return protoreflect.ValueOfString("")
	case "defihub.financiamento.Emprestimo.devedor":
		return protoreflect.ValueOfString("")
	case "defihub.financiamento.Emprestimo.credor":
		return protoreflect.ValueOfString("")
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: defihub.financiamento.Emprestimo"))
		}
		panic(fmt.Errorf("message defihub.financiamento.Emprestimo does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_Emprestimo) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in defihub.financiamento.Emprestimo", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_Emprestimo) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Emprestimo) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_Emprestimo) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_Emprestimo) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*Emprestimo)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if x.Id != 0 {
			n += 1 + runtime.Sov(uint64(x.Id))
		}
		if x.Valor != 0 {
			n += 1 + runtime.Sov(uint64(x.Valor))
		}
		if x.Prazo != 0 {
			n += 1 + runtime.Sov(uint64(x.Prazo))
		}
		l = len(x.Taxa)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Devedor)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Credor)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*Emprestimo)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.Credor) > 0 {
			i -= len(x.Credor)
			copy(dAtA[i:], x.Credor)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Credor)))
			i--
			dAtA[i] = 0x32
		}
		if len(x.Devedor) > 0 {
			i -= len(x.Devedor)
			copy(dAtA[i:], x.Devedor)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Devedor)))
			i--
			dAtA[i] = 0x2a
		}
		if len(x.Taxa) > 0 {
			i -= len(x.Taxa)
			copy(dAtA[i:], x.Taxa)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Taxa)))
			i--
			dAtA[i] = 0x22
		}
		if x.Prazo != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Prazo))
			i--
			dAtA[i] = 0x18
		}
		if x.Valor != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Valor))
			i--
			dAtA[i] = 0x10
		}
		if x.Id != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Id))
			i--
			dAtA[i] = 0x8
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*Emprestimo)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Emprestimo: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Emprestimo: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
				}
				x.Id = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Id |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 2:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Valor", wireType)
				}
				x.Valor = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Valor |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 3:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Prazo", wireType)
				}
				x.Prazo = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Prazo |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Taxa", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Taxa = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 5:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Devedor", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Devedor = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 6:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Credor", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Credor = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: defihub/financiamento/emprestimo.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Emprestimo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Valor   uint64 `protobuf:"varint,2,opt,name=valor,proto3" json:"valor,omitempty"`
	Prazo   uint64 `protobuf:"varint,3,opt,name=prazo,proto3" json:"prazo,omitempty"`
	Taxa    string `protobuf:"bytes,4,opt,name=taxa,proto3" json:"taxa,omitempty"`
	Devedor string `protobuf:"bytes,5,opt,name=devedor,proto3" json:"devedor,omitempty"`
	Credor  string `protobuf:"bytes,6,opt,name=credor,proto3" json:"credor,omitempty"`
}

func (x *Emprestimo) Reset() {
	*x = Emprestimo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_defihub_financiamento_emprestimo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Emprestimo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Emprestimo) ProtoMessage() {}

// Deprecated: Use Emprestimo.ProtoReflect.Descriptor instead.
func (*Emprestimo) Descriptor() ([]byte, []int) {
	return file_defihub_financiamento_emprestimo_proto_rawDescGZIP(), []int{0}
}

func (x *Emprestimo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Emprestimo) GetValor() uint64 {
	if x != nil {
		return x.Valor
	}
	return 0
}

func (x *Emprestimo) GetPrazo() uint64 {
	if x != nil {
		return x.Prazo
	}
	return 0
}

func (x *Emprestimo) GetTaxa() string {
	if x != nil {
		return x.Taxa
	}
	return ""
}

func (x *Emprestimo) GetDevedor() string {
	if x != nil {
		return x.Devedor
	}
	return ""
}

func (x *Emprestimo) GetCredor() string {
	if x != nil {
		return x.Credor
	}
	return ""
}

var File_defihub_financiamento_emprestimo_proto protoreflect.FileDescriptor

var file_defihub_financiamento_emprestimo_proto_rawDesc = []byte{
	0x0a, 0x26, 0x64, 0x65, 0x66, 0x69, 0x68, 0x75, 0x62, 0x2f, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63,
	0x69, 0x61, 0x6d, 0x65, 0x6e, 0x74, 0x6f, 0x2f, 0x65, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x74, 0x69,
	0x6d, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x64, 0x65, 0x66, 0x69, 0x68, 0x75,
	0x62, 0x2e, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x69, 0x61, 0x6d, 0x65, 0x6e, 0x74, 0x6f, 0x22,
	0x8e, 0x01, 0x0a, 0x0a, 0x45, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x74, 0x69, 0x6d, 0x6f, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x61, 0x7a, 0x6f, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x05, 0x70, 0x72, 0x61, 0x7a, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61,
	0x78, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x78, 0x61, 0x12, 0x18,
	0x0a, 0x07, 0x64, 0x65, 0x76, 0x65, 0x64, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x64, 0x65, 0x76, 0x65, 0x64, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x72, 0x65, 0x64,
	0x6f, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x72, 0x65, 0x64, 0x6f, 0x72,
	0x42, 0xdc, 0x01, 0x0a, 0x19, 0x63, 0x6f, 0x6d, 0x2e, 0x64, 0x65, 0x66, 0x69, 0x68, 0x75, 0x62,
	0x2e, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x69, 0x61, 0x6d, 0x65, 0x6e, 0x74, 0x6f, 0x42, 0x0f,
	0x45, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x74, 0x69, 0x6d, 0x6f, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50,
	0x01, 0x5a, 0x39, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x61,
	0x62, 0x72, 0x69, 0x65, 0x6c, 0x73, 0x63, 0x6f, 0x74, 0x61, 0x2f, 0x64, 0x65, 0x66, 0x69, 0x68,
	0x75, 0x62, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x65, 0x66, 0x69, 0x68, 0x75, 0x62, 0x2f, 0x66,
	0x69, 0x6e, 0x61, 0x6e, 0x63, 0x69, 0x61, 0x6d, 0x65, 0x6e, 0x74, 0x6f, 0xa2, 0x02, 0x03, 0x44,
	0x46, 0x58, 0xaa, 0x02, 0x15, 0x44, 0x65, 0x66, 0x69, 0x68, 0x75, 0x62, 0x2e, 0x46, 0x69, 0x6e,
	0x61, 0x6e, 0x63, 0x69, 0x61, 0x6d, 0x65, 0x6e, 0x74, 0x6f, 0xca, 0x02, 0x15, 0x44, 0x65, 0x66,
	0x69, 0x68, 0x75, 0x62, 0x5c, 0x46, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x69, 0x61, 0x6d, 0x65, 0x6e,
	0x74, 0x6f, 0xe2, 0x02, 0x21, 0x44, 0x65, 0x66, 0x69, 0x68, 0x75, 0x62, 0x5c, 0x46, 0x69, 0x6e,
	0x61, 0x6e, 0x63, 0x69, 0x61, 0x6d, 0x65, 0x6e, 0x74, 0x6f, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x16, 0x44, 0x65, 0x66, 0x69, 0x68, 0x75, 0x62,
	0x3a, 0x3a, 0x46, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x69, 0x61, 0x6d, 0x65, 0x6e, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_defihub_financiamento_emprestimo_proto_rawDescOnce sync.Once
	file_defihub_financiamento_emprestimo_proto_rawDescData = file_defihub_financiamento_emprestimo_proto_rawDesc
)

func file_defihub_financiamento_emprestimo_proto_rawDescGZIP() []byte {
	file_defihub_financiamento_emprestimo_proto_rawDescOnce.Do(func() {
		file_defihub_financiamento_emprestimo_proto_rawDescData = protoimpl.X.CompressGZIP(file_defihub_financiamento_emprestimo_proto_rawDescData)
	})
	return file_defihub_financiamento_emprestimo_proto_rawDescData
}

var file_defihub_financiamento_emprestimo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_defihub_financiamento_emprestimo_proto_goTypes = []interface{}{
	(*Emprestimo)(nil), // 0: defihub.financiamento.Emprestimo
}
var file_defihub_financiamento_emprestimo_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_defihub_financiamento_emprestimo_proto_init() }
func file_defihub_financiamento_emprestimo_proto_init() {
	if File_defihub_financiamento_emprestimo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_defihub_financiamento_emprestimo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Emprestimo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_defihub_financiamento_emprestimo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_defihub_financiamento_emprestimo_proto_goTypes,
		DependencyIndexes: file_defihub_financiamento_emprestimo_proto_depIdxs,
		MessageInfos:      file_defihub_financiamento_emprestimo_proto_msgTypes,
	}.Build()
	File_defihub_financiamento_emprestimo_proto = out.File
	file_defihub_financiamento_emprestimo_proto_rawDesc = nil
	file_defihub_financiamento_emprestimo_proto_goTypes = nil
	file_defihub_financiamento_emprestimo_proto_depIdxs = nil
}
