// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: defihub/financiamento/tx.proto

package financiamento

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Msg_UpdateParams_FullMethodName        = "/defihub.financiamento.Msg/UpdateParams"
	Msg_SolicitarEmprestimo_FullMethodName = "/defihub.financiamento.Msg/SolicitarEmprestimo"
	Msg_AprovarEmprestimo_FullMethodName   = "/defihub.financiamento.Msg/AprovarEmprestimo"
	Msg_PagarEmprestimo_FullMethodName     = "/defihub.financiamento.Msg/PagarEmprestimo"
)

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MsgClient interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	SolicitarEmprestimo(ctx context.Context, in *MsgSolicitarEmprestimo, opts ...grpc.CallOption) (*MsgSolicitarEmprestimoResponse, error)
	AprovarEmprestimo(ctx context.Context, in *MsgAprovarEmprestimo, opts ...grpc.CallOption) (*MsgAprovarEmprestimoResponse, error)
	PagarEmprestimo(ctx context.Context, in *MsgPagarEmprestimo, opts ...grpc.CallOption) (*MsgPagarEmprestimoResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateParams_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SolicitarEmprestimo(ctx context.Context, in *MsgSolicitarEmprestimo, opts ...grpc.CallOption) (*MsgSolicitarEmprestimoResponse, error) {
	out := new(MsgSolicitarEmprestimoResponse)
	err := c.cc.Invoke(ctx, Msg_SolicitarEmprestimo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) AprovarEmprestimo(ctx context.Context, in *MsgAprovarEmprestimo, opts ...grpc.CallOption) (*MsgAprovarEmprestimoResponse, error) {
	out := new(MsgAprovarEmprestimoResponse)
	err := c.cc.Invoke(ctx, Msg_AprovarEmprestimo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) PagarEmprestimo(ctx context.Context, in *MsgPagarEmprestimo, opts ...grpc.CallOption) (*MsgPagarEmprestimoResponse, error) {
	out := new(MsgPagarEmprestimoResponse)
	err := c.cc.Invoke(ctx, Msg_PagarEmprestimo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations must embed UnimplementedMsgServer
// for forward compatibility
type MsgServer interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	SolicitarEmprestimo(context.Context, *MsgSolicitarEmprestimo) (*MsgSolicitarEmprestimoResponse, error)
	AprovarEmprestimo(context.Context, *MsgAprovarEmprestimo) (*MsgAprovarEmprestimoResponse, error)
	PagarEmprestimo(context.Context, *MsgPagarEmprestimo) (*MsgPagarEmprestimoResponse, error)
	mustEmbedUnimplementedMsgServer()
}

// UnimplementedMsgServer must be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (UnimplementedMsgServer) UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (UnimplementedMsgServer) SolicitarEmprestimo(context.Context, *MsgSolicitarEmprestimo) (*MsgSolicitarEmprestimoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SolicitarEmprestimo not implemented")
}
func (UnimplementedMsgServer) AprovarEmprestimo(context.Context, *MsgAprovarEmprestimo) (*MsgAprovarEmprestimoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AprovarEmprestimo not implemented")
}
func (UnimplementedMsgServer) PagarEmprestimo(context.Context, *MsgPagarEmprestimo) (*MsgPagarEmprestimoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PagarEmprestimo not implemented")
}
func (UnimplementedMsgServer) mustEmbedUnimplementedMsgServer() {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SolicitarEmprestimo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSolicitarEmprestimo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SolicitarEmprestimo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_SolicitarEmprestimo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SolicitarEmprestimo(ctx, req.(*MsgSolicitarEmprestimo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_AprovarEmprestimo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAprovarEmprestimo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).AprovarEmprestimo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_AprovarEmprestimo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).AprovarEmprestimo(ctx, req.(*MsgAprovarEmprestimo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_PagarEmprestimo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgPagarEmprestimo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).PagarEmprestimo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_PagarEmprestimo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).PagarEmprestimo(ctx, req.(*MsgPagarEmprestimo))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "defihub.financiamento.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "SolicitarEmprestimo",
			Handler:    _Msg_SolicitarEmprestimo_Handler,
		},
		{
			MethodName: "AprovarEmprestimo",
			Handler:    _Msg_AprovarEmprestimo_Handler,
		},
		{
			MethodName: "PagarEmprestimo",
			Handler:    _Msg_PagarEmprestimo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "defihub/financiamento/tx.proto",
}
