// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: defihub/financiamento/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"

	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgUpdateParams is the Msg/UpdateParams request type.
type MsgUpdateParams struct {
	// authority is the address that controls the module (defaults to x/gov unless overwritten).
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// NOTE: All parameters must be supplied.
	Params Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params"`
}

func (m *MsgUpdateParams) Reset()         { *m = MsgUpdateParams{} }
func (m *MsgUpdateParams) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParams) ProtoMessage()    {}
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c43e1e9d3f395c4, []int{0}
}
func (m *MsgUpdateParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParams.Merge(m, src)
}
func (m *MsgUpdateParams) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParams.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParams proto.InternalMessageInfo

func (m *MsgUpdateParams) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateParams) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// MsgUpdateParamsResponse defines the response structure for executing a
// MsgUpdateParams message.
type MsgUpdateParamsResponse struct {
}

func (m *MsgUpdateParamsResponse) Reset()         { *m = MsgUpdateParamsResponse{} }
func (m *MsgUpdateParamsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParamsResponse) ProtoMessage()    {}
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c43e1e9d3f395c4, []int{1}
}
func (m *MsgUpdateParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParamsResponse.Merge(m, src)
}
func (m *MsgUpdateParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParamsResponse proto.InternalMessageInfo

type MsgSolicitarEmprestimo struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Valor   uint64 `protobuf:"varint,2,opt,name=valor,proto3" json:"valor,omitempty"`
	Prazo   uint64 `protobuf:"varint,3,opt,name=prazo,proto3" json:"prazo,omitempty"`
	Taxa    string `protobuf:"bytes,4,opt,name=taxa,proto3" json:"taxa,omitempty"`
}

func (m *MsgSolicitarEmprestimo) Reset()         { *m = MsgSolicitarEmprestimo{} }
func (m *MsgSolicitarEmprestimo) String() string { return proto.CompactTextString(m) }
func (*MsgSolicitarEmprestimo) ProtoMessage()    {}
func (*MsgSolicitarEmprestimo) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c43e1e9d3f395c4, []int{2}
}
func (m *MsgSolicitarEmprestimo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSolicitarEmprestimo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSolicitarEmprestimo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSolicitarEmprestimo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSolicitarEmprestimo.Merge(m, src)
}
func (m *MsgSolicitarEmprestimo) XXX_Size() int {
	return m.Size()
}
func (m *MsgSolicitarEmprestimo) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSolicitarEmprestimo.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSolicitarEmprestimo proto.InternalMessageInfo

func (m *MsgSolicitarEmprestimo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgSolicitarEmprestimo) GetValor() uint64 {
	if m != nil {
		return m.Valor
	}
	return 0
}

func (m *MsgSolicitarEmprestimo) GetPrazo() uint64 {
	if m != nil {
		return m.Prazo
	}
	return 0
}

func (m *MsgSolicitarEmprestimo) GetTaxa() string {
	if m != nil {
		return m.Taxa
	}
	return ""
}

type MsgSolicitarEmprestimoResponse struct {
}

func (m *MsgSolicitarEmprestimoResponse) Reset()         { *m = MsgSolicitarEmprestimoResponse{} }
func (m *MsgSolicitarEmprestimoResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSolicitarEmprestimoResponse) ProtoMessage()    {}
func (*MsgSolicitarEmprestimoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c43e1e9d3f395c4, []int{3}
}
func (m *MsgSolicitarEmprestimoResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSolicitarEmprestimoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSolicitarEmprestimoResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSolicitarEmprestimoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSolicitarEmprestimoResponse.Merge(m, src)
}
func (m *MsgSolicitarEmprestimoResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSolicitarEmprestimoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSolicitarEmprestimoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSolicitarEmprestimoResponse proto.InternalMessageInfo

type MsgAprovarEmprestimo struct {
	Creator      string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	EmprestimoId uint64 `protobuf:"varint,2,opt,name=emprestimoId,proto3" json:"emprestimoId,omitempty"`
}

func (m *MsgAprovarEmprestimo) Reset()         { *m = MsgAprovarEmprestimo{} }
func (m *MsgAprovarEmprestimo) String() string { return proto.CompactTextString(m) }
func (*MsgAprovarEmprestimo) ProtoMessage()    {}
func (*MsgAprovarEmprestimo) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c43e1e9d3f395c4, []int{4}
}
func (m *MsgAprovarEmprestimo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAprovarEmprestimo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAprovarEmprestimo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAprovarEmprestimo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAprovarEmprestimo.Merge(m, src)
}
func (m *MsgAprovarEmprestimo) XXX_Size() int {
	return m.Size()
}
func (m *MsgAprovarEmprestimo) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAprovarEmprestimo.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAprovarEmprestimo proto.InternalMessageInfo

func (m *MsgAprovarEmprestimo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgAprovarEmprestimo) GetEmprestimoId() uint64 {
	if m != nil {
		return m.EmprestimoId
	}
	return 0
}

type MsgAprovarEmprestimoResponse struct {
}

func (m *MsgAprovarEmprestimoResponse) Reset()         { *m = MsgAprovarEmprestimoResponse{} }
func (m *MsgAprovarEmprestimoResponse) String() string { return proto.CompactTextString(m) }
func (*MsgAprovarEmprestimoResponse) ProtoMessage()    {}
func (*MsgAprovarEmprestimoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c43e1e9d3f395c4, []int{5}
}
func (m *MsgAprovarEmprestimoResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAprovarEmprestimoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAprovarEmprestimoResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAprovarEmprestimoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAprovarEmprestimoResponse.Merge(m, src)
}
func (m *MsgAprovarEmprestimoResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgAprovarEmprestimoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAprovarEmprestimoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAprovarEmprestimoResponse proto.InternalMessageInfo

type MsgPagarEmprestimo struct {
	Creator      string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	EmprestimoId uint64 `protobuf:"varint,2,opt,name=emprestimoId,proto3" json:"emprestimoId,omitempty"`
	Valor        uint64 `protobuf:"varint,3,opt,name=valor,proto3" json:"valor,omitempty"`
}

func (m *MsgPagarEmprestimo) Reset()         { *m = MsgPagarEmprestimo{} }
func (m *MsgPagarEmprestimo) String() string { return proto.CompactTextString(m) }
func (*MsgPagarEmprestimo) ProtoMessage()    {}
func (*MsgPagarEmprestimo) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c43e1e9d3f395c4, []int{6}
}
func (m *MsgPagarEmprestimo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgPagarEmprestimo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgPagarEmprestimo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgPagarEmprestimo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgPagarEmprestimo.Merge(m, src)
}
func (m *MsgPagarEmprestimo) XXX_Size() int {
	return m.Size()
}
func (m *MsgPagarEmprestimo) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgPagarEmprestimo.DiscardUnknown(m)
}

var xxx_messageInfo_MsgPagarEmprestimo proto.InternalMessageInfo

func (m *MsgPagarEmprestimo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgPagarEmprestimo) GetEmprestimoId() uint64 {
	if m != nil {
		return m.EmprestimoId
	}
	return 0
}

func (m *MsgPagarEmprestimo) GetValor() uint64 {
	if m != nil {
		return m.Valor
	}
	return 0
}

type MsgPagarEmprestimoResponse struct {
}

func (m *MsgPagarEmprestimoResponse) Reset()         { *m = MsgPagarEmprestimoResponse{} }
func (m *MsgPagarEmprestimoResponse) String() string { return proto.CompactTextString(m) }
func (*MsgPagarEmprestimoResponse) ProtoMessage()    {}
func (*MsgPagarEmprestimoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c43e1e9d3f395c4, []int{7}
}
func (m *MsgPagarEmprestimoResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgPagarEmprestimoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgPagarEmprestimoResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgPagarEmprestimoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgPagarEmprestimoResponse.Merge(m, src)
}
func (m *MsgPagarEmprestimoResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgPagarEmprestimoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgPagarEmprestimoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgPagarEmprestimoResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgUpdateParams)(nil), "defihub.financiamento.MsgUpdateParams")
	proto.RegisterType((*MsgUpdateParamsResponse)(nil), "defihub.financiamento.MsgUpdateParamsResponse")
	proto.RegisterType((*MsgSolicitarEmprestimo)(nil), "defihub.financiamento.MsgSolicitarEmprestimo")
	proto.RegisterType((*MsgSolicitarEmprestimoResponse)(nil), "defihub.financiamento.MsgSolicitarEmprestimoResponse")
	proto.RegisterType((*MsgAprovarEmprestimo)(nil), "defihub.financiamento.MsgAprovarEmprestimo")
	proto.RegisterType((*MsgAprovarEmprestimoResponse)(nil), "defihub.financiamento.MsgAprovarEmprestimoResponse")
	proto.RegisterType((*MsgPagarEmprestimo)(nil), "defihub.financiamento.MsgPagarEmprestimo")
	proto.RegisterType((*MsgPagarEmprestimoResponse)(nil), "defihub.financiamento.MsgPagarEmprestimoResponse")
}

func init() { proto.RegisterFile("defihub/financiamento/tx.proto", fileDescriptor_0c43e1e9d3f395c4) }

var fileDescriptor_0c43e1e9d3f395c4 = []byte{
	// 554 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xbf, 0x6f, 0xd3, 0x40,
	0x14, 0x8e, 0x49, 0x5a, 0x94, 0x47, 0xa4, 0xaa, 0x47, 0xa0, 0xae, 0x55, 0x4c, 0xe4, 0x01, 0x4a,
	0x50, 0x63, 0xb5, 0x55, 0x19, 0x32, 0xd1, 0x48, 0x0c, 0x0c, 0x11, 0x55, 0x2a, 0x16, 0x16, 0x74,
	0x71, 0x2e, 0xd7, 0x93, 0x62, 0x9f, 0x75, 0x77, 0x89, 0x52, 0x58, 0x2a, 0x46, 0x26, 0xfe, 0x0c,
	0xc6, 0x0c, 0xfc, 0x0f, 0x74, 0xac, 0x98, 0x60, 0x41, 0x28, 0x19, 0xf2, 0x6f, 0x20, 0xff, 0x4a,
	0x88, 0xe3, 0x48, 0xa9, 0xc4, 0x62, 0xdf, 0x7b, 0xef, 0xbb, 0xef, 0xfb, 0xde, 0xf9, 0xf9, 0xc0,
	0xec, 0x90, 0x2e, 0xbb, 0xe8, 0xb7, 0xed, 0x2e, 0xf3, 0xb0, 0xe7, 0x30, 0xec, 0x12, 0x4f, 0x71,
	0x5b, 0x0d, 0x6b, 0xbe, 0xe0, 0x8a, 0xa3, 0x07, 0x71, 0xbd, 0xb6, 0x50, 0x37, 0xb6, 0xb1, 0xcb,
	0x3c, 0x6e, 0x87, 0xcf, 0x08, 0x69, 0xec, 0x38, 0x5c, 0xba, 0x5c, 0xda, 0xae, 0xa4, 0xf6, 0xe0,
	0x30, 0x78, 0xc5, 0x85, 0xdd, 0xa8, 0xf0, 0x3e, 0x8c, 0xec, 0x28, 0x88, 0x4b, 0x65, 0xca, 0x29,
	0x8f, 0xf2, 0xc1, 0x2a, 0xce, 0x5a, 0xd9, 0x9e, 0x7c, 0x2c, 0xb0, 0x1b, 0xef, 0xb4, 0xbe, 0x6b,
	0xb0, 0xd5, 0x94, 0xf4, 0xad, 0xdf, 0xc1, 0x8a, 0x9c, 0x85, 0x15, 0xf4, 0x02, 0x8a, 0xb8, 0xaf,
	0x2e, 0xb8, 0x60, 0xea, 0x52, 0xd7, 0x2a, 0xda, 0x7e, 0xb1, 0xa1, 0xff, 0xf8, 0x76, 0x50, 0x8e,
	0x25, 0x4f, 0x3b, 0x1d, 0x41, 0xa4, 0x3c, 0x57, 0x82, 0x79, 0xb4, 0x35, 0x87, 0xa2, 0x97, 0xb0,
	0x19, 0x71, 0xeb, 0x77, 0x2a, 0xda, 0xfe, 0xbd, 0xa3, 0x47, 0xb5, 0xcc, 0xa6, 0x6b, 0x91, 0x4c,
	0xa3, 0x78, 0xfd, 0xfb, 0x71, 0xee, 0xeb, 0x74, 0x54, 0xd5, 0x5a, 0xf1, 0xbe, 0x7a, 0xfd, 0xd3,
	0x74, 0x54, 0x9d, 0x33, 0x7e, 0x9e, 0x8e, 0xaa, 0x4f, 0x93, 0x26, 0x86, 0xa9, 0x36, 0x52, 0xae,
	0xad, 0x5d, 0xd8, 0x49, 0xa5, 0x5a, 0x44, 0xfa, 0xdc, 0x93, 0xc4, 0xba, 0xd2, 0xe0, 0x61, 0x53,
	0xd2, 0x73, 0xde, 0x63, 0x0e, 0x53, 0x58, 0xbc, 0x72, 0x7d, 0x41, 0xa4, 0x62, 0x2e, 0x47, 0x3a,
	0xdc, 0x75, 0x04, 0xc1, 0x8a, 0x8b, 0xa8, 0xd3, 0x56, 0x12, 0xa2, 0x32, 0x6c, 0x0c, 0x70, 0x8f,
	0x8b, 0xb0, 0x99, 0x42, 0x2b, 0x0a, 0x82, 0xac, 0x2f, 0xf0, 0x07, 0xae, 0xe7, 0xa3, 0x6c, 0x18,
	0x20, 0x04, 0x05, 0x85, 0x87, 0x58, 0x2f, 0x84, 0x14, 0xe1, 0xba, 0x5e, 0x0a, 0x7a, 0x49, 0xd8,
	0xac, 0x0a, 0x98, 0xd9, 0x0e, 0x66, 0x26, 0xdb, 0x50, 0x6e, 0x4a, 0x7a, 0xea, 0x0b, 0x3e, 0x58,
	0xd3, 0xa1, 0x05, 0x25, 0x32, 0xc3, 0xbd, 0xee, 0xc4, 0x46, 0x17, 0x72, 0x29, 0x17, 0x26, 0xec,
	0x65, 0x69, 0xcc, 0x3c, 0x0c, 0x00, 0x35, 0x25, 0x3d, 0xc3, 0xf4, 0xff, 0x39, 0x98, 0x9f, 0x63,
	0xfe, 0x9f, 0x73, 0x4c, 0xf9, 0xda, 0x03, 0x63, 0x59, 0x37, 0x71, 0x75, 0xf4, 0x2b, 0x0f, 0xf9,
	0xa6, 0xa4, 0xa8, 0x0b, 0xa5, 0x85, 0x39, 0x7d, 0xb2, 0x62, 0xbe, 0x52, 0x63, 0x60, 0xd4, 0xd6,
	0xc3, 0x25, 0x7a, 0xe8, 0x23, 0xdc, 0xcf, 0x1a, 0x95, 0x83, 0xd5, 0x34, 0x19, 0x70, 0xe3, 0xe4,
	0x56, 0xf0, 0x99, 0x78, 0x1f, 0xb6, 0x97, 0x67, 0xe0, 0xf9, 0x6a, 0xae, 0x25, 0xb0, 0x71, 0x7c,
	0x0b, 0xf0, 0x4c, 0x96, 0xc3, 0x56, 0xfa, 0xb3, 0x3f, 0x5b, 0xcd, 0x93, 0x82, 0x1a, 0x87, 0x6b,
	0x43, 0x13, 0x41, 0x63, 0xe3, 0x2a, 0xf8, 0xf3, 0x1b, 0x6f, 0xae, 0xc7, 0xa6, 0x76, 0x33, 0x36,
	0xb5, 0x3f, 0x63, 0x53, 0xfb, 0x32, 0x31, 0x73, 0x37, 0x13, 0x33, 0xf7, 0x73, 0x62, 0xe6, 0xde,
	0x9d, 0x50, 0xa6, 0x02, 0x46, 0x87, 0xbb, 0x36, 0xc5, 0x6d, 0xc1, 0x48, 0x4f, 0x3a, 0x5c, 0x61,
	0x7b, 0xd5, 0x85, 0xa0, 0x2e, 0x7d, 0x22, 0xdb, 0x9b, 0xe1, 0xbd, 0x76, 0xfc, 0x37, 0x00, 0x00,
	0xff, 0xff, 0x71, 0xca, 0x00, 0xb6, 0x91, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	SolicitarEmprestimo(ctx context.Context, in *MsgSolicitarEmprestimo, opts ...grpc.CallOption) (*MsgSolicitarEmprestimoResponse, error)
	AprovarEmprestimo(ctx context.Context, in *MsgAprovarEmprestimo, opts ...grpc.CallOption) (*MsgAprovarEmprestimoResponse, error)
	PagarEmprestimo(ctx context.Context, in *MsgPagarEmprestimo, opts ...grpc.CallOption) (*MsgPagarEmprestimoResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, "/defihub.financiamento.Msg/UpdateParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SolicitarEmprestimo(ctx context.Context, in *MsgSolicitarEmprestimo, opts ...grpc.CallOption) (*MsgSolicitarEmprestimoResponse, error) {
	out := new(MsgSolicitarEmprestimoResponse)
	err := c.cc.Invoke(ctx, "/defihub.financiamento.Msg/SolicitarEmprestimo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) AprovarEmprestimo(ctx context.Context, in *MsgAprovarEmprestimo, opts ...grpc.CallOption) (*MsgAprovarEmprestimoResponse, error) {
	out := new(MsgAprovarEmprestimoResponse)
	err := c.cc.Invoke(ctx, "/defihub.financiamento.Msg/AprovarEmprestimo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) PagarEmprestimo(ctx context.Context, in *MsgPagarEmprestimo, opts ...grpc.CallOption) (*MsgPagarEmprestimoResponse, error) {
	out := new(MsgPagarEmprestimoResponse)
	err := c.cc.Invoke(ctx, "/defihub.financiamento.Msg/PagarEmprestimo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	SolicitarEmprestimo(context.Context, *MsgSolicitarEmprestimo) (*MsgSolicitarEmprestimoResponse, error)
	AprovarEmprestimo(context.Context, *MsgAprovarEmprestimo) (*MsgAprovarEmprestimoResponse, error)
	PagarEmprestimo(context.Context, *MsgPagarEmprestimo) (*MsgPagarEmprestimoResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) UpdateParams(ctx context.Context, req *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (*UnimplementedMsgServer) SolicitarEmprestimo(ctx context.Context, req *MsgSolicitarEmprestimo) (*MsgSolicitarEmprestimoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SolicitarEmprestimo not implemented")
}
func (*UnimplementedMsgServer) AprovarEmprestimo(ctx context.Context, req *MsgAprovarEmprestimo) (*MsgAprovarEmprestimoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AprovarEmprestimo not implemented")
}
func (*UnimplementedMsgServer) PagarEmprestimo(ctx context.Context, req *MsgPagarEmprestimo) (*MsgPagarEmprestimoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PagarEmprestimo not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/defihub.financiamento.Msg/UpdateParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SolicitarEmprestimo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSolicitarEmprestimo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SolicitarEmprestimo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/defihub.financiamento.Msg/SolicitarEmprestimo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SolicitarEmprestimo(ctx, req.(*MsgSolicitarEmprestimo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_AprovarEmprestimo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAprovarEmprestimo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).AprovarEmprestimo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/defihub.financiamento.Msg/AprovarEmprestimo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).AprovarEmprestimo(ctx, req.(*MsgAprovarEmprestimo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_PagarEmprestimo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgPagarEmprestimo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).PagarEmprestimo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/defihub.financiamento.Msg/PagarEmprestimo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).PagarEmprestimo(ctx, req.(*MsgPagarEmprestimo))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "defihub.financiamento.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "SolicitarEmprestimo",
			Handler:    _Msg_SolicitarEmprestimo_Handler,
		},
		{
			MethodName: "AprovarEmprestimo",
			Handler:    _Msg_AprovarEmprestimo_Handler,
		},
		{
			MethodName: "PagarEmprestimo",
			Handler:    _Msg_PagarEmprestimo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "defihub/financiamento/tx.proto",
}

func (m *MsgUpdateParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgSolicitarEmprestimo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSolicitarEmprestimo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSolicitarEmprestimo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Taxa) > 0 {
		i -= len(m.Taxa)
		copy(dAtA[i:], m.Taxa)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Taxa)))
		i--
		dAtA[i] = 0x22
	}
	if m.Prazo != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Prazo))
		i--
		dAtA[i] = 0x18
	}
	if m.Valor != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Valor))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSolicitarEmprestimoResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSolicitarEmprestimoResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSolicitarEmprestimoResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgAprovarEmprestimo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAprovarEmprestimo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAprovarEmprestimo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.EmprestimoId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.EmprestimoId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgAprovarEmprestimoResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAprovarEmprestimoResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAprovarEmprestimoResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgPagarEmprestimo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgPagarEmprestimo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgPagarEmprestimo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Valor != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Valor))
		i--
		dAtA[i] = 0x18
	}
	if m.EmprestimoId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.EmprestimoId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgPagarEmprestimoResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgPagarEmprestimoResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgPagarEmprestimoResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgUpdateParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Params.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgSolicitarEmprestimo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Valor != 0 {
		n += 1 + sovTx(uint64(m.Valor))
	}
	if m.Prazo != 0 {
		n += 1 + sovTx(uint64(m.Prazo))
	}
	l = len(m.Taxa)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSolicitarEmprestimoResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgAprovarEmprestimo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.EmprestimoId != 0 {
		n += 1 + sovTx(uint64(m.EmprestimoId))
	}
	return n
}

func (m *MsgAprovarEmprestimoResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgPagarEmprestimo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.EmprestimoId != 0 {
		n += 1 + sovTx(uint64(m.EmprestimoId))
	}
	if m.Valor != 0 {
		n += 1 + sovTx(uint64(m.Valor))
	}
	return n
}

func (m *MsgPagarEmprestimoResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgUpdateParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSolicitarEmprestimo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSolicitarEmprestimo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSolicitarEmprestimo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Valor", wireType)
			}
			m.Valor = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Valor |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Prazo", wireType)
			}
			m.Prazo = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Prazo |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Taxa", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Taxa = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSolicitarEmprestimoResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSolicitarEmprestimoResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSolicitarEmprestimoResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAprovarEmprestimo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAprovarEmprestimo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAprovarEmprestimo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EmprestimoId", wireType)
			}
			m.EmprestimoId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EmprestimoId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAprovarEmprestimoResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAprovarEmprestimoResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAprovarEmprestimoResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgPagarEmprestimo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgPagarEmprestimo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgPagarEmprestimo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EmprestimoId", wireType)
			}
			m.EmprestimoId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EmprestimoId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Valor", wireType)
			}
			m.Valor = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Valor |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgPagarEmprestimoResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgPagarEmprestimoResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgPagarEmprestimoResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
